# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-glue-iam
  description: This component provisions IAM roles for AWS Glue
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component









